name: munhelper
services:
  api:
    build: .
    image: mahasvan/munhelper-api:latest
    container_name: api
    ports:
      - "${API_ACCESS_PORT}:5000"
    environment:
      - CHAT_MODEL=${OLLAMA_MODEL}
      - OLLAMA_BASE_URL=http://ollama:${OLLAMA_PORT}
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=${CHROMA_PORT}
      - CHROMA_COLLECTION=${CHROMA_COLLECTION}
      - IS_CONTAINER=docker
    restart: always
    pull_policy: missing
    depends_on:
      ollama:
        condition: service_healthy

  chromadb:
    image: chromadb/chroma:latest
    environment:
      - ANONYMIZED_TELEMETRY=False
    # healthcheck:
    #   test: [ "CMD", "curl", "http://localhost:8000/api/v1", "-f" ]
    #   start_period: 10s
    #   interval: 1m
    #   start_interval: 1s
    #   timeout: 3s
    #   retries: 30
    restart: always
    volumes:
      - chroma-data:/chroma/chroma

  ollama:
    build:
      context: ./ollama
      args:
        OLLAMA_MODEL: ${OLLAMA_MODEL}
        OLLAMA_PORT: ${OLLAMA_PORT}
    image: mahasvan/munhelper-ollama:latest
    container_name: ollama
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:${OLLAMA_PORT}/", "-f" ]
      start_period: 20s
      interval: 1m
      start_interval: 1s
      timeout: 30s
      retries: 5
    restart: always
    pull_policy: missing

  frontend:
    build: ./frontend
    image: mahasvan/munhelper-frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: always
    pull_policy: missing
volumes:
  chroma-data: