name: munhelper
services:
  api:
    image: mahasvan/munhelper-api:latest
    ports:
      - "5000:5000"
    environment:
      - CHAT_MODEL=${OLLAMA_MODEL}
      - OLLAMA_BASE_URL=http://ollama:11434
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - CHROMA_COLLECTION=${CHROMA_COLLECTION}
    depends_on:
      chromadb:
        condition: service_healthy
      ollama:
        condition: service_healthy

  chromadb:
    image: chromadb/chroma:latest
    environment:
      - ANONYMIZED_TELEMETRY=False
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8000/api/v1", "-f" ]
      start_period: 10s
      interval: 1m
      start_interval: 1s
      timeout: 3s
      retries: 30
    volumes:
      - chroma-data:/chroma/chroma
  ollama:
    image: mahasvan/munhelper-ollama:gemma-2b
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:11434/", "-f" ]
      start_period: 20s
      interval: 1m
      start_interval: 1s
      timeout: 30s
      retries: 5

  frontend:
    image: mahasvan/munhelper-frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
volumes:
  chroma-data: