name: munhelper
services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - CHAT_MODEL=${CHAT_MODEL}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - CHROMA_COLLECTION=${CHROMA_COLLECTION}
    depends_on:
      chromadb:
        condition: service_healthy
  chromadb:
    image: chromadb/chroma:latest
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8000/docs", "-f"]
      interval: 5s
      timeout: 3s
      retries: 30
    ports:
      - "8000:8000"
